name: ProtectYourself
main: com.github.alexresh.Main
version: 1.0.0
api-version: 1.16
commands:
  i:
    description: Show inspection
    usage: /i
  white:
    description: Add user to whitelist and give him 30 days
    usage: /white nick